language: node_js
node_js:
- "node"
 
required: sudo

services:
- docker

deploy:
  provider: heroku
  app: angular-project-manager
  api_key:
    secure: "bac688af-1a37-49b2-bfe1-8846ccd02ce0"


before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

